wordpress:
  page: 'https://biovoxel.tech/wp-admin'
  username: 'specify_user'
  password: 'specify_pass'
posta:
  page: 'https://mojezasielky.posta.sk/'
  username: 'specify_user'
  password: 'specify_pass'
# for browser use chrome or firefox
browser: 'chrome'
